// Movies App Actions
export const SEARCH_MOVIES = 'SEARCH_MOVIES'
export const SEARCH_MOVIES_RESPONSE = 'SEARCH_MOVIES_RESPONSE'
export const OBTENER_DATOS_MESA_ACTA = 'OBTENER_DATOS_MESA_ACTA'
export const OBTENER_DATOS_MESA_ACTA_RESPONSE = 'OBTENER_DATOS_MESA_ACTA_RESPONSE'